### ISSUE TITLE
Can't see the encryption key

### ISSUE THREAD

**Issue by reg3xp** [NekoX-Dev/NekoX#648]
**Describe the bug**
Can't see the encryption key and QR code in secret chat
It shows a blank page

**To Reproduce**
1. Open encryption key section in secret chat.

**Smartphone (please complete the following information):**
 - Device: Samsung galaxy S10
 - OS: Android 11
 - Version: 8.1.1 (F-Droid)

**Comment by JosephPelletier** [comment]
I have the same issue: op means to say "key visualization", there should not be a qr code

Steps to reproduce:

1: open any secret chat
2: tap your partner's name
3: tap encryption key

you will see a blank screen with no info.
a key visualization and fingerprint should be on screen.

The keys represented in these photos are no longer in use

The bug
![blank screen](https://user-images.githubusercontent.com/77814012/140128531-953b649b-9ee2-4ba4-8d85-4f3ac44067f3.jpg)

The expected behavior
![expected data](https://user-images.githubusercontent.com/77814012/140132069-c18e28e9-505c-4777-bdc8-3b85f79776ec.jpg)


Reproduced with
device: google pixel 3a
OS: Android 11, LineageOS 18.1
NekoX: 8.1.1-arm64 (f-droid)

I'd tell you the version the problem came about but I cannot downgrade.
Hopefully this is enough to close in on the problem. Thanks so much for your work, its appreciated greatly.

**Comment by reg3xp** [comment]
Update: 
Fixed in 8.2.3-1-arm64 F-Droid

**Comment by centerpoint67** [comment]
@JosephPelletier can you confirm so @arm64v8a can close this
